name: Deploy Microsoft 365 Agent app

on:
  workflow_dispatch:
  push:
    paths:
      - 'appPackage/**'
      - 'm365agents.yml'
      - '.github/workflows/m365-deploy.yml'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MICROSOFT_365_AGENTS_TOOLKIT_CLI_VERSION: "1.0.1"
      AZURE_SERVICE_PRINCIPAL_CLIENT_ID: ${{ vars.AZURE_SERVICE_PRINCIPAL_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET: ${{ secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET }}
      BOT_AZURE_APP_SERVICE_RESOURCE_ID: ${{ vars.BOT_AZURE_APP_SERVICE_RESOURCE_ID }}
      TEAMS_APP_ID: ${{ vars.TEAMS_APP_ID }}
      # Add extra environment variables here so that atk cli can use them.

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup Node 20.x
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: install cli
        run: |
          npm install @microsoft/m365agentstoolkit-cli@${{env.MICROSOFT_365_AGENTS_TOOLKIT_CLI_VERSION}}

      - name: Login Azure by service principal
        run: |
          npx atk auth login azure --username ${{vars.AZURE_SERVICE_PRINCIPAL_CLIENT_ID}}  \
          --service-principal true \
          --tenant ${{vars.AZURE_TENANT_ID}} \
          --password ${{secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET }} \
          --interactive false

      # - name: Deploy to hosting environment
      #   run: |
      #     npx atk deploy --ignore-env-file true \
      #     --interactive false

      - name: Package app
        run: |
          npx atk package

      - name: upload appPackage
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: appPackage/build/appPackage.zip

      - name: Publish appPackage
        run: |
          npx atk publish \
          --interactive false
